protected/models/Presensi.php
<?php

/**
 * This is the model class for table "presensi".
 *
 * The followings are the available columns in table 'presensi':
 * @property string $status
 * @property string $tanggal
 * @property integer $nis
 * @property string $th_ajar
 * @property string $semester
 *
 * The followings are the available model relations:
 * @property Siswa $nis0
 * @property SemesterAktif $thAjar
 * @property SemesterAktif $semester0
 */
class Presensi extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Presensi the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'presensi';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('status, tanggal, nis, th_ajar, semester', 'required'),
			array('nis', 'numerical', 'integerOnly'=>true),
			array('status, semester', 'length', 'max'=>1),
			array('th_ajar', 'length', 'max'=>10),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('status, tanggal, nis, th_ajar, semester', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'nis0' => array(self::BELONGS_TO, 'Siswa', 'nis'),
			'thAjar' => array(self::BELONGS_TO, 'SemesterAktif', 'th_ajar'),
			'semester0' => array(self::BELONGS_TO, 'SemesterAktif', 'semester'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'status' => 'Status',
			'tanggal' => 'Tanggal',
			'nis' => 'Nis',
			'th_ajar' => 'Th Ajar',
			'semester' => 'Semester',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('status',$this->status,true);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('nis',$this->nis);
		$criteria->compare('th_ajar',$this->th_ajar,true);
		$criteria->compare('semester',$this->semester,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function raport()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.
		$bulan=date('m');
		if($bulan<7){
			$smt=2;
			//jika th 2(1-6) maka tahun-1/tahun-2 2012/2013
			$th_ajar=(date('Y')-1).'/'.date('Y');
		}elseif($bulan<13 && $bulan>6){
			$smt=1;
			//jika th 1(7-12) maka tahun/tahun+1 2012/2013
			$th_ajar=date('Y').'/'.(date('Y')+1);
		}
		
		$criteria = new CDbCriteria(array(
				'condition' => "nis='".$_GET['id']."' and th_ajar='".$th_ajar."' and semester='".$smt."'",
		));
	
		$criteria->compare('status',$this->status,true);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('nis',$this->nis);
		$criteria->compare('th_ajar',$this->th_ajar,true);
		$criteria->compare('semester',$this->semester,true);
	
		return new CActiveDataProvider($this, array(
				'criteria'=>$criteria,
		));
	}
	
	public function this_presensi()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.
	
		$criteria = new CDbCriteria(array(
			'condition' => "tanggal='".date('Y-m-d')."'",
		));
	
		$criteria->compare('status',$this->status,true);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('nis',$this->nis);
		$criteria->compare('th_ajar',$this->th_ajar,true);
		$criteria->compare('semester',$this->semester,true);
	
		return new CActiveDataProvider($this, array(
				'criteria'=>$criteria,
		));
	}
	
	public function all_presensi()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.
	
		$bulan=date('m');
		if($bulan<7){
			$smt=2;
			//jika th 2(1-6) maka tahun-1/tahun-2 2012/2013
			$th_ajar=(date('Y')-1).'/'.date('Y');
		}elseif($bulan<13 && $bulan>6){
			$smt=1;
			//jika th 1(7-12) maka tahun/tahun+1 2012/2013
			$th_ajar=date('Y').'/'.(date('Y')+1);
		}
		
		$criteria=new CDbCriteria;
		$criteria->compare('semester',$smt,true);
		$criteria->compare('th_ajar',$th_ajar,true);
	
		$criteria->compare('status',$this->status,true);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('nis',$this->nis);
	
		return new CActiveDataProvider($this, array(
				'criteria'=>$criteria,
		));
	}
}

protected/controllers/PresensiController.php
<?php

class PresensiController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'rights',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	/*public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}*/

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id,$id2,$id3,$id4)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id,$id2,$id3,$id4),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$this->layout='//layouts/column1';
		//Action search dialog
		$model2=new Penempatan('gurupiket');
		$model2->unsetAttributes();  // clear any default values
		if(isset($_GET['Penempatan']))
			$model2->attributes=$_GET['Penempatan'];
		
		//Action create
		$model=new Presensi;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		if(isset($_POST['Presensi']))
		{
			$model->attributes=$_POST['Presensi'];
			try {
				if($model->save()){
					if($model->tanggal==date('Y-m-d')){
						$model->save();
						Yii::app()->user->setFlash('success', 'Data <strong>berhasil</strong> disimpan.');
						$this->redirect(array('index'));
					}else{
						Yii::app()->user->setFlash('error', '<strong>Input tanggal maksimal hari ini.</strong> Terima Kasih');
						$model->addError(null, "Input tanggal maksimal hari ini. Terima Kasih"/*$e->getMessage()*/);
					}
				}
			}
			catch(CDbException $e) {
				Yii::app()->user->setFlash('warning', 'Maaf <strong>data sudah ada dalam database</strong>. Silahkan periksa kembali');
				//$model->addError(null, $e->getMessage());
				$model->addError(null, "Maaf <strong>data sudah ada dalam database</strong>. Silahkan periksa kembali");
			}
		}

		$this->render('create',array(
			'model'=>$model,
			'model2'=>$model2,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id,$id2,$id3,$id4)
	{
		$this->layout='//layouts/column1';
		$model=$this->loadModel($id,$id2,$id3,$id4);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Presensi']))
		{
			$model->attributes=$_POST['Presensi'];
			if($model->save())
				Yii::app()->user->setFlash('success', 'Data <strong>berhasil</strong> diperbarui. Terima kasih');
				$this->redirect(array('view','id'=>$model->nis, 'id2'=>$model->tanggal, 'id3'=>$model->th_ajar, 'id4'=>$model->semester));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id,$id2,$id3,$id4)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id,$id2,$id3,$id4)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				Yii::app()->user->setFlash('success', 'Data <strong>berhasil</strong> dihapus. Terima kasih');
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->layout='//layouts/column1';
		$model=new Presensi('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Presensi']))
			$model->attributes=$_GET['Presensi'];
		
		$dataProvider=new CActiveDataProvider('Presensi');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionArsip()
	{
		$this->layout='//layouts/column1';
		$model=new Presensi('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Presensi'])){
			if(($_GET['Presensi']['nis'])==0 && ($_GET['Presensi']['nis'])!=null){
				$model->attributes=$_GET['Presensi'];
				Yii::app()->user->setFlash('warning', 'Data gagal diproses. <b>NIS</b> tidak boleh kosong atau 0');
			}else{
				$model->attributes=$_GET['Presensi'];
				Yii::app()->user->setFlash('success', 'Data berhasil diproses. Terima kasih');
			}
		}else $model->nis = 0;

		$this->render('arsip',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id,$id2,$id3,$id4)
	{
		$model=Presensi::model()->findByPk(array('nis'=>$id,'tanggal'=>$id2, 'th_ajar'=>$id3, 'semester'=>$id4));
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='presensi-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/presensi/_dialogpiket.php
<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'penempatanpikets-grid',
	'dataProvider'=>Penempatan::model()->gurupiket(),
	'type'=>'striped bordered condensed',
	'filter'=>$model2,
	'columns'=>array(
		'nis',
		'nis0.nama_lengkap',
		'kelas',
		'lokal',
		array(
				'header'=>'',
				'type'=>'raw',
				'value'=>'CHtml::Button(
		        "+"
		        , array(
		        "name" => "get_link"
		        , "id" => "get_link"
		        , "onClick" => "$(\"#mydialog\").dialog(\"close\");$(\"#Presensi_nis \").val(\"". $data->nis."\");"))',
		),
	),
)); ?>

protected/views/presensi/_dialogwali.php
<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'penempatanwali-grid',
	'dataProvider'=>$model2->search2(),
	'type'=>'striped bordered condensed',
	'filter'=>$model2,
	'columns'=>array(
		'nis',
		'nis0.nama_lengkap',
		'kelas',
		'lokal',
		array(
				'header'=>'',
				'type'=>'raw',
				'value'=>'CHtml::Button(
		        "+"
		        , array(
		        "name" => "get_link"
		        , "id" => "get_link"
		        , "onClick" => "$(\"#mydialog\").dialog(\"close\");$(\"#Presensi_nis \").val(\"". $data->nis."\");"))',
		),
	),
)); ?>

protected/views/presensi/_form.php
	<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
		'id'=>'presensi-form',
		'type'=>'horizontal',
		'enableAjaxValidation'=>false,
		'focus'=>array($model,'nis'),
	)); ?>

	<!-- <p class="help-block">Fields with <span class="required">*</span> are required.</p> -->
	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'nis',array('class'=>'span5', 
	'hint' => 'Silahkan tekan tombol <a href="#" onclick=$("#mydialog").dialog("open"); return false; class="btn submit">+</a> untuk melihat daftar siswa.')); ?>
	
	<?php echo $form->radioButtonListRow($model, 'status', array('S'=>'Sakit', 'I'=>'Izin', 'A'=>'Alpha')); ?>
	
	<?php //echo $form->textFieldRow($model,'tanggal',array('class'=>'span2', 'value'=>date('Y-m-d'))); ?>
	<?php echo $form->datepickerRow($model,'tanggal',array('class'=>'span5', 'value'=>date('Y-m-d'),'options'=>array('dateFormat'=> 'yy-mm-dd'),));?>
	<?php 
		$bulan=date('m');
		if($bulan<7){
			$smt=2;
			//jika th 2(1-6) maka tahun-1/tahun-2 2012/2013
			$th_ajar=(date('Y')-1).'/'.date('Y');
		}elseif($bulan<13 && $bulan>6){
			$smt=1;
			//jika th 1(7-12) maka tahun/tahun+1 2012/2013
			$th_ajar=date('Y').'/'.(date('Y')+1);
		}
	?>

	<?php //$th_ajar=Yii::app()->db->createCommand("select th_ajar from semester_aktif order by th_ajar DESC limit 1;")->queryScalar(); ?>
	<?php echo $form->hiddenField($model,'th_ajar',array('class'=>'span5','maxlength'=>10, 'value'=>$th_ajar)); ?>

	<?php //$semester=Yii::app()->db->createCommand("select semester from semester_aktif where semester='".$smt."' limit 1;")->queryScalar(); ?>
	<?php echo $form->hiddenField($model,'semester',array('class'=>'span5','maxlength'=>1, 'value'=>$smt)); ?>
	
	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'danger',
			'icon'=>'icon-plus icon-white',
			'label'=>$model->isNewRecord ? 'Tambah' : 'Save',
		)); ?>
		
		<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'reset', 'label'=>'Ulangi', 'icon'=>'icon-refresh icon-white','type'=>'danger'));	?>
		
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'type'=>'danger',
			'icon'=>'icon-share-alt icon-white',
			'label'=>'Kembali',
			'url'=>array('index')
		)); ?>
	</div>

<?php $this->endWidget(); ?>


<?php 
    $this->beginWidget('zii.widgets.jui.CJuiDialog',array(
    'id'=>'mydialog',
    // additional javascript options for the dialog plugin
    'options'=>array(
        'title'=>'Klik tanda <code>+</code> untuk input data siswa',
        'autoOpen'=>false,
		'modal' => true,
		'show'=>array(
				'effect'=>'blind',
				'duration'=>1000,
		),
		'hide'=>array(
				'effect'=>'explode',
				'duration'=>500,
		),
		'width' => 640, 
		'height' => 480
    ),
));?>
<?php 
	if(Yii::app()->user->checkAccess('Admin')){
		$this->widget('bootstrap.widgets.TbTabs', array(
				'type' => 'tabs', // 'tabs' or 'pills'
				'placement'=>'above', // 'above', 'right', 'below' or 'left'
				'tabs' => array(
						array('label' => 'WALI', 'active'=>true, 'visible'=>Yii::app()->user->checkAccess('Wali'), 'icon'=>'icon-list-alt', 'content' => $this->renderPartial('_dialogwali', array('model'=>$model, 'model2'=>$model2), true)),
						array('label' => 'GURU PIKET', 'visible'=>Yii::app()->user->checkAccess('Piket'), 'icon'=>'icon-list-alt', 'content' => $this->renderPartial('_dialogpiket', array('model'=>$model, 'model2'=>$model2), true)),
				),
		));
	}else{
		$this->widget('bootstrap.widgets.TbTabs', array(
				'type' => 'tabs', // 'tabs' or 'pills'
				'placement'=>'above', // 'above', 'right', 'below' or 'left'
				'tabs' => array(
						array('label' => 'WALI', 'active'=>true, 'visible'=>Yii::app()->user->checkAccess('Wali'), 'icon'=>'icon-list-alt', 'content' => $this->renderPartial('_dialogwali', array('model'=>$model, 'model2'=>$model2), true)),
						array('label' => 'GURU PIKET', 'active'=>true, 'visible'=>Yii::app()->user->checkAccess('Piket'), 'icon'=>'icon-list-alt', 'content' => $this->renderPartial('_dialogpiket', array('model'=>$model, 'model2'=>$model2), true)),
				),
		));
	}
?>
<?php	$this->endWidget('zii.widgets.jui.CJuiDialog'); ?>

protected/views/presensi/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
	'type'=>'horizontal',
	'focus'=>array($model,'nis'),
)); ?>

	<?php //echo $form->textFieldRow($model,'tanggal',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'nis',array('class'=>'span5')); ?>
	
	<?php $th_ajar = CHtml::listData(SemesterAktif::model()->findAll(array(
		'order'=>'th_ajar ASC',
		'select' => 'th_ajar',
		'distinct' => true,
		)), 'th_ajar', 'th_ajar');
	?>
	<?php echo $form->dropDownListRow($model, 'th_ajar', $th_ajar, array('class'=>'span5', 'empty' => '-- Pilih Tahun --', 'rel'=>'tooltip', 'data-placement'=>'right', 'title'=>'Langkah 1 Pilih tahun')); ?>

	<?php $smt = CHtml::listData(SemesterAktif::model()->findAll(array(
		'order'=>'semester ASC',
		'select' => 'semester',
		'distinct' => true,
		)), 'semester', 'semester');
	?>
	<?php echo $form->dropDownListRow($model, 'semester', $smt, array('class'=>'span5', 'empty' => '-- Pilih Semester --', 'rel'=>'tooltip', 'data-placement'=>'right', 'title'=>'Langkah 1 Pilih semester')); ?>

	<?php echo $form->dropDownListRow($model, 'status', array('S'=>'Sakit', 'I'=>'Izin', 'A'=>'Alpha'), array('class'=>'span5', 'empty' => '-- Pilih Status Kehadiran --', 'rel'=>'tooltip', 'data-placement'=>'right', 'title'=>'Langkah 1 Pilih status')); ?>
	
	<?php //echo $form->textFieldRow($model,'th_ajar',array('class'=>'span5','maxlength'=>10)); ?>

	<?php //echo $form->textFieldRow($model,'semester',array('class'=>'span5','maxlength'=>1)); ?>
	
	<?php //echo $form->textFieldRow($model,'status',array('class'=>'span5','maxlength'=>1)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'danger',
			'icon'=>'icon-search icon-white',
			'label'=>'CARI ',
			'htmlOptions' => array('rel'=>'tooltip', 'data-placement'=>'left', 'title'=>'Langkah 2 Klik untuk melihat hasil')
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/presensi/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('tanggal')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->tanggal),array('view','id'=>$data->nis, 'id2'=>$data->tanggal, 'id3'=>$data->th_ajar, 'id4'=>$data->semester)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nis')); ?>:</b>
	<?php echo CHtml::encode($data->nis); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('th_ajar')); ?>:</b>
	<?php echo CHtml::encode($data->th_ajar); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('semester')); ?>:</b>
	<?php echo CHtml::encode($data->semester); ?>
	<br />


</div>

protected/views/presensi/all_presensi.php
<?php
$this->breadcrumbs=array(
	'Absensis'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Absensi','url'=>array('index')),
	array('label'=>'Create Absensi','url'=>array('create')),
);

?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'presensi2-grid',
	'dataProvider'=>$model->all_presensi(),
	'type'=>'striped bordered condensed',
	'enableSorting'=>false,
	//'filter'=>$model,
	'columns'=>array(
		array(
				'header' => 'No',
				'value' => '$row+1',
				'htmlOptions'=>array('style'=>'width: 20px')
		),
		'nis',
		'nis0.nama_lengkap',
		'status',
		'tanggal',
		'th_ajar',
		'semester',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			//'template'=>'{view}{update}{delete}',
			'template'=>'{view}',
			'header'=>'Lihat',
			'buttons'=>array
					('view'=>array
							(
								'url'=>'Yii::app()->createUrl("presensi/view", array("id"=>$data->nis,"id2"=>$data->tanggal,"id3"=>$data->th_ajar,"id4"=>$data->semester))',
							),
					),
		),
	),
)); ?>

protected/views/presensi/arsip.php
<?php
$this->breadcrumbs=array(
	'Absensis'=>array('index'),
	'Arsip',
);

$this->menu=array(
	array('label'=>'List Absensi','url'=>array('index')),
	array('label'=>'Create Absensi','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('presensi-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<?php $box = $this->beginWidget('bootstrap.widgets.TbBox', array(
	'title' => 'ARSIP PRESENSI SISWA',
	'headerIcon' => 'icon-book',
	'htmlOptions'=>array('class'=>'inline'),
	// when displaying a table, if we include bootstra-widget-table class
	// the table will be 0-padding to the box
));?>
<div class="search-form2">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'presensi-grid',
	'dataProvider'=>$model->search(),
	'type'=>'striped bordered condensed',
	'enableSorting'=>false,
	//'filter'=>$model,
	'columns'=>array(
		'nis',
		'nis0.nama_lengkap',
		'status',
		'tanggal',
		'th_ajar',
		'semester',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			//'template'=>'{view}{update}{delete}',
			'template'=>'{view}',
			'header'=>'Lihat',
			'buttons'=>array
					('view'=>array
							(
								'url'=>'Yii::app()->createUrl("presensi/view", array("id"=>$data->nis,"id2"=>$data->tanggal,"id3"=>$data->th_ajar,"id4"=>$data->semester))',
							),
					),
		),
	),
)); ?>
<?php $this->endWidget(); ?>

protected/views/presensi/this_presensi.php
<?php
$this->breadcrumbs=array(
	'Absensis'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Absensi','url'=>array('index')),
	array('label'=>'Create Absensi','url'=>array('create')),
);

?>
<?php $this->widget('bootstrap.widgets.TbExtendedGridView', array(
	'id'=>'presensi1-grid',
	'dataProvider'=>$model->this_presensi(),
	'type'=>'striped bordered condensed',
	'enableSorting'=>false,
	//'filter'=>$model,
	'columns'=>array(
		array(
				'header' => 'No',
				'value' => '$row+1',
				'htmlOptions'=>array('style'=>'width: 20px')
		),
		'nis',
		'nis0.nama_lengkap',
		'status',
		'tanggal',
		'th_ajar',
		'semester',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			//'template'=>'{view}{update}{delete}',
			'template'=>'{view}',
			'header'=>'Lihat',
			'buttons'=>array
					('view'=>array
							(
								'url'=>'Yii::app()->createUrl("presensi/view", array("id"=>$data->nis,"id2"=>$data->tanggal,"id3"=>$data->th_ajar,"id4"=>$data->semester))',
							),
					),
		),
	),
)); ?>