protected/models/Kecamatan.php
<?php

/**
 * This is the model class for table "kecamatan".
 *
 * The followings are the available columns in table 'kecamatan':
 * @property integer $idkab
 * @property string $nama_kec
 * @property integer $idkec
 *
 * The followings are the available model relations:
 * @property AsalSekolah[] $asalSekolahs
 * @property Pendaftar[] $pendaftars
 * @property Wali[] $walis
 * @property Siswa[] $siswas
 * @property Kabupaten $idkab0
 * @property Guru[] $gurus
 */
class Kecamatan extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Kecamatan the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'kecamatan';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('idkab, nama_kec, idkec', 'required'),
			array('idkab, idkec', 'numerical', 'integerOnly'=>true),
			array('nama_kec', 'length', 'max'=>30),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('idkab, nama_kec, idkec', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'asalSekolahs' => array(self::HAS_MANY, 'AsalSekolah', 'idkec'),
			'pendaftars' => array(self::HAS_MANY, 'Pendaftar', 'idkec'),
			'walis' => array(self::HAS_MANY, 'Wali', 'idkec'),
			'siswas' => array(self::HAS_MANY, 'Siswa', 'idkec'),
			'idkab0' => array(self::BELONGS_TO, 'Kabupaten', 'idkab'),
			'gurus' => array(self::HAS_MANY, 'Guru', 'idkec'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idkab' => 'Idkab',
			'nama_kec' => 'Nama Kec',
			'idkec' => 'Idkec',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idkab',$this->idkab);
		$criteria->compare('nama_kec',$this->nama_kec,true);
		$criteria->compare('idkec',$this->idkec);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function getCityOptionsByState($idkab) {
		if(empty($idkab))
			$idkab = null;
	
		$kecamatan = self::model()->findAll('idkab=:idkab order by nama_kec',array('idkab'=>$idkab));
	
		$kec = CHtml::listData($kecamatan, 'idkec', 'nama_kec');
		return $kec;
	}
}

protected/controllers/KecamatanController.php
<?php

class KecamatanController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'rights',
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	/*public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}*/

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Kecamatan;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kecamatan']))
		{
			$namakec=Yii::app()->db->createCommand("select nama_kab from kecamatan where idkec='".$_POST['Kecamatan']['idkec']."';")->queryScalar();
			$model->attributes=$_POST['Kecamatan'];
			$model->nama_kec=$namakec;
			if($model->save())
				$this->redirect(array('view','id'=>$model->idkec));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kecamatan']))
		{
			$model->attributes=$_POST['Kecamatan'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->idkec));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Kecamatan');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Kecamatan('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Kecamatan']))
			$model->attributes=$_GET['Kecamatan'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Kecamatan::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='kecamatan-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	/*public function actionFilterkab()
	{
	
		$data=Kabupaten::model()->findAll('idprop=:idprop',
				array(':idprop'=>(int) $_POST['idprop']));
	
		$data=CHtml::listData($data,'idkab','nama_kab');
		foreach($data as $value=>$name)
		{
			echo CHtml::tag('option',array('value'=>$value),CHtml::encode($name),true);
		}
	
	}
	
	public function actionFilterkec()
	{
	
		$data=Kecamatan::model()->findAll('idkab=:idkab',
				array(':idkab'=>(int) $_POST['idkab']));
	
		$data=CHtml::listData($data,'idkec','nama_kec');
		foreach($data as $value=>$name)
		{
			echo CHtml::tag('option',array('value'=>$value),CHtml::encode($name),true);
		}
	}*/
	
	// untuk Kabupaten
	public function actionKabupatenku()
	{
		$propinsi = $_POST['Kecamatan']['idprop'];
		$models = Kabupaten::model()->findAll("idprop=':propinsi'", array(':propinsi'=>$propinsi));
	
		$kabupaten = CHtml::tag('option',array('value'=>'' ),CHtml::encode('Pilih Kabupaten'),true);
		foreach($models as $model)
		{
			$kabupaten.=CHtml::tag('option',array('value'=>$model->idkab), CHtml::encode($model->nama_kab), true);
		}
	
		echo CJSON::encode(array(
				'error'=>'false',
				'kabupaten'=>$kabupaten,
		));
	
		Yii::app()->end();
	}
	// untuk kecamatan
	public function actionKecamatanku()
	{
		$propinsi = $_POST['Kecamatan']['idprop'];
		$kabupaten = $_POST['Kecamatan']['idkab'];
		$models = Kecamatan::model()->findAll('idprop=:propinsi AND idkab=:kabupaten', array(':propinsi'=>$propinsi, ':kabupaten'=>$kabupaten));
	
		$kecamatan = CHtml::tag('option',array('value'=>'' ),CHtml::encode('Pilih Kecamatan'),true);
		foreach($models as $model)
		{
			$kecamatan.=CHtml::tag('option',array('value'=>$model->idkec), CHtml::encode($model->nama_kec), true);
		}
	
		echo CJSON::encode(array(
				'error'=>'false',
				'kecamatan'=>$kecamatan,
		));
		Yii::app()->end();
	}
	
	public function actionDinamis2() {
		$data2 = Kabupaten::model()->getStateOptions($_POST['idprop']);
	
		foreach ($data2 as $value2 => $name2) {
			echo CHtml::tag('option', array('value' => $value2), CHtml::encode($name2), true);
		}
	}
	
	public function actionDinamis() {
		$data = Kecamatan::model()->getCityOptionsByState($_POST['idkab']);
	
		foreach ($data as $value => $name) {
			echo CHtml::tag('option', array('value' => $value), CHtml::encode($name), true);
		}
	}
}

protected/views/kecamatan/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'kecamatan-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>
<p>   
<?php echo CHtml::dropDownList('idprop','', CHtml::listData(Propinsi::model()->getPropinsi(),'idprop','nama_prop'),
			array('empty' => 'Pilih Prop', 'ajax' => array(  
            'type'=>'POST', //request type  
            'url'=>CController::createUrl('kabupaten/dinamis2'), //url to call.  
            'data'=>'js:"idprop="+jQuery(this).val()',  
            'update'=>'#idkab', //selector to update  
            ))); ?>  
   
</p>

<p>   
    <?php 
    $idprop=Yii::app()->db->createCommand("select idprop from kabupaten;")->queryScalar();

    		echo $form->dropDownList($model,'idkab', Kabupaten::model()->getStateOptions($idprop), array('id'=>'idkab','empty' => 'Pilih Kab', 'ajax' => array(  
            'type'=>'POST', //request type  
            'url'=>CController::createUrl('kecamatan/dinamis'), //url to call.  
            'data'=>'js:"idkab="+jQuery(this).val()',  
            'update'=>'#idkec', //selector to update  
            ))); ?>  
   
</p>  
  
<p>    
    <?php echo $form->dropDownList($model,'idkec',Kecamatan::model()->getCityOptionsByState($model->idkab), array('id'=>'idkec'));?> 
</p> 

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/kecamatan/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'idkab',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'nama_kec',array('class'=>'span5','maxlength'=>30)); ?>

	<?php echo $form->textFieldRow($model,'idkec',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/kecamatan/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idkec')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idkec),array('view','id'=>$data->idkec)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idkab')); ?>:</b>
	<?php echo CHtml::encode($data->idkab); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nama_kec')); ?>:</b>
	<?php echo CHtml::encode($data->nama_kec); ?>
	<br />


</div>

protected/views/kecamatan/admin.php
<?php
$this->breadcrumbs=array(
	'Kecamatans'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Kecamatan','url'=>array('index')),
	array('label'=>'Create Kecamatan','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('kecamatan-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Kecamatans</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'kecamatan-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'idkab',
		'nama_kec',
		'idkec',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/kecamatan/create.php
<?php
$this->breadcrumbs=array(
	'Kecamatans'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Kecamatan','url'=>array('index')),
	array('label'=>'Manage Kecamatan','url'=>array('admin')),
);
?>

<h1>Create Kecamatan</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/kecamatan/index.php
<?php
$this->breadcrumbs=array(
	'Kecamatans',
);

$this->menu=array(
	array('label'=>'Create Kecamatan','url'=>array('create')),
	array('label'=>'Manage Kecamatan','url'=>array('admin')),
);
?>

<h1>Kecamatans</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/kecamatan/update.php
<?php
$this->breadcrumbs=array(
	'Kecamatans'=>array('index'),
	$model->idkec=>array('view','id'=>$model->idkec),
	'Update',
);

$this->menu=array(
	array('label'=>'List Kecamatan','url'=>array('index')),
	array('label'=>'Create Kecamatan','url'=>array('create')),
	array('label'=>'View Kecamatan','url'=>array('view','id'=>$model->idkec)),
	array('label'=>'Manage Kecamatan','url'=>array('admin')),
);
?>

<h1>Update Kecamatan <?php echo $model->idkec; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/kecamatan/view.php
<?php
$this->breadcrumbs=array(
	'Kecamatans'=>array('index'),
	$model->idkec,
);

$this->menu=array(
	array('label'=>'List Kecamatan','url'=>array('index')),
	array('label'=>'Create Kecamatan','url'=>array('create')),
	array('label'=>'Update Kecamatan','url'=>array('update','id'=>$model->idkec)),
	array('label'=>'Delete Kecamatan','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->idkec),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Kecamatan','url'=>array('admin')),
);
?>

<h1>View Kecamatan #<?php echo $model->idkec; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'idkab',
		'nama_kec',
		'idkec',
	),
)); ?>